name: Lint Pull Requests for UID2Prebid

on:
  pull_request:
    paths:
      - UID2Prebid.podspec.json

  # this allows us to manually run this job
  workflow_dispatch:

jobs:
  lint-podspec:
    name: Lint UID2Prebid Podspec
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.4
        run: sudo xcode-select -s /Applications/Xcode_16.4.app

      - name: Lint OpenPass podspec
        run: pod lib lint UID2Prebid.podspec.json --verbose
